simplification

diff --git a/src/bin/rs b/src/bin/rs
--- a/src/bin/rs
+++ b/src/bin/rs
@@ -17,71 +17,27 @@
 # spp_autoend : auto clean-up function run on target
 # spp_autoendlocal : auto clean-up function run on local host
 #
-
 set -euf -o pipefail
-mydir="$(cd "$(dirname "$0")" && pwd)"
 
-if [ -L "$0" ] ; then
-  basedir=$(dirname $(readlink -f "$0"))
-  if [ -d "$(dirname "$basedir")/lib/ashlib/ashlib" ] ; then
-    ashlib="$(dirname "$basedir")/lib/ashlib/ashlib"
-  elif [ -d "$(dirname "$basedir")/lib/ashlib/lib" ] ; then
-    ashlib="$(dirname "$basedir")/lib/ashlib/lib"
-  elif [ -d "$(dirname "$basedir")/lib/ashlib" ] ; then
-    ashlib="$(dirname "$basedir")/lib/ashlib"
-  elif [ -d "$(dirname "$basedir")/ashlib" ] ; then
-    ashlib="$(dirname "$basedir")/ashlib"
-  elif [ -f "$(dirname "$basedir")/lib/ashlib.sh" ] ; then
-    ashlib="$(dirname "$basedir")/lib"
-  else
-    echo "Missing ashlib folder" 1>&2
-    exit 36
-  fi
+O0="$0" ; [ -n "${ORIG0:-}" ] && O0="${ORIG0}"
+mydir=$(readlink -f "$(dirname "$O0")")
+srcdir=$(dirname "$0")
+
+if [ -n "${ASHLIB:-}" ] ; then
+  ashlib="$ASHLIB"
+elif [ -d "$srcdir/../ashlib" ] ; then
+  ashlib="$srcdir/../ashlib"
+elif [ -d "$srcdir/../lib/ashlib" ] ; then
+  ashlib="$srcdir/../lib/ashlib"
+elif [ -d "$srcdir/ashlib" ] ; then
+  ashlib="$srcdir/ashlib"
+elif [ -d "$srcdir/lib/ashlib" ] ; then
+  ashlib="$srcdir/lib/ashlib"
 else
-  # First check if submodules are there...
-  if [ -d "$mydir/.git" ] ; then
-    if [ -f "$mydir/.gitmodules" ] ; then
-      # Check if submodules are all there...
-      grep -E '^\s*path\s*=\s*' "$mydir"/.gitmodules | sed 's/^\s*path\s*=\s*//' | while read subpath
-      do
-	if [ ! -e "$mydir/$subpath/.git" ] ; then
-	  (cd "$mydir" && git submodule update --init --recursive)
-	  break
-	fi
-      done
-    fi
-  fi
-
-  if [ -L "$mydir/.ashlib" ] ; then
-    # Check if there is a run-time file...
-    ashlib="$mydir/.ashlib/ashlib"
-  elif [ -d "$mydir/ashlib/src/ashlib" ] ; then
-    ashlib="$mydir/ashlib/src/ashlib"
-  elif [ -d "$mydir/modules/ashlib/src/ashlib" ] ; then
-    ashlib="$mydir/modules/ashlib/src/ashlib"
-  elif [ -d "$(dirname "$mydir")/ashlib" ] ; then
-    ashlib="$(dirname "$mydir")/ashlib"
-  else
-    echo "Missing \"ashlib\"" 1>&2
-    exit 1
-  fi
-
-  rs_src=$(dirname "$ashlib")/bin/rs
-
-  if [ ! -f "$rs_src" ] ; then
-    echo "Missing \"rs\" source script" 1>&2
-    exit 68
-  fi
-
-  # Make sure this script and the submodule are in sync...
-  if ! cmp "$0" "$rs_src" >/dev/null 2>&1 ; then
-    echo "Updating $0..." 1>&2
-    rm -f "$0"
-    cp -a "$$rs_src" "$0"
-    exec "$SHELL" "$0" "$@"
-    exit $?
-  fi
+  echo "Missing \"ashlib\"" 1>&2
+  exit 1
 fi
+ashlib=$(readlink -f "$ashlib")
 
 export ASHLIB="$ashlib"
 . "$ashlib/ashlib.sh"
